version: '3'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    command:
      - 'yarn'
      - 'start'
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"