name: 
title: 
email: 
description: 
baseurl: ""
url: ""
robots: true
google_analytics_code: 
collections:
  pages:
    output: true
    permalink: /:path/

# Build settings
markdown: kramdown
theme: 
plugins:
  - jekyll-feed
